export const icreateContentsConfig = {
    // chant it
    'PP1': {
        1: { courseCode: '7923', url: '/Contents/LCMSContents/143001-144000/143740/index.html', runType: ''},
        2: { courseCode: '9322', url: '/Contents/LCMSContents/146001-147000/146391/index.html', runType: ''},
        3: { courseCode: '9323', url: '/Contents/LCMSContents/146001-147000/146392/index.html', runType: ''},
        4: { courseCode: '9324', url: '/Contents/LCMSContents/146001-147000/146393/index.html', runType: ''},
        5: { courseCode: '', url: '', runType: ''},
        6: { courseCode: '', url: '', runType: ''},
        7: { courseCode: '', url: '', runType: ''},
        8: { courseCode: '', url: '', runType: ''},
        9: { courseCode: '', url: '', runType: ''},
        10: { courseCode: '', url: '', runType: ''},
        12: { courseCode: '', url: '', runType: ''},
        13: { courseCode: '', url: '', runType: ''},
        14: { courseCode: '', url: '', runType: ''},
        15: { courseCode: '', url: '', runType: ''},
        16: { courseCode: '', url: '', runType: ''},
        17: { courseCode: '', url: '', runType: ''},
        18: { courseCode: '', url: '', runType: ''},
        19: { courseCode: '', url: '', runType: ''},
        20: { courseCode: '', url: '', runType: ''},
        21: { courseCode: '', url: '', runType: ''},
        22: { courseCode: '', url: '', runType: ''},
        23: { courseCode: '', url: '', runType: ''},
        24: { courseCode: '', url: '', runType: ''},
    },
    // say it
    'MP1': {
        1: { courseCode: '7903', url: '/Contents/LCMSContents/143001-144000/143712/index.html', runType: 'chant'},
        2: { courseCode: '9711', url: '/Contents/LCMSContents/147001-148000/147025/index.html', runType: 'chant'},
        3: { courseCode: '9712', url: '/Contents/LCMSContents/147001-148000/147026/index.html', runType: 'chant'},
        4: { courseCode: '9713', url: '/Contents/LCMSContents/147001-148000/147027/index.html', runType: 'chant'},
        5: { courseCode: '', url: '', runType: ''},
        6: { courseCode: '', url: '', runType: ''},
        7: { courseCode: '', url: '', runType: ''},
        8: { courseCode: '', url: '', runType: ''},
        9: { courseCode: '', url: '', runType: ''},
        10: { courseCode: '', url: '', runType: ''},
        12: { courseCode: '', url: '', runType: ''},
        13: { courseCode: '', url: '', runType: ''},
        14: { courseCode: '', url: '', runType: ''},
        15: { courseCode: '', url: '', runType: ''},
        16: { courseCode: '', url: '', runType: ''},
        17: { courseCode: '', url: '', runType: ''},
        18: { courseCode: '', url: '', runType: ''},
        19: { courseCode: '', url: '', runType: ''},
        20: { courseCode: '', url: '', runType: ''},
        21: { courseCode: '', url: '', runType: ''},
        22: { courseCode: '', url: '', runType: ''},
        23: { courseCode: '', url: '', runType: ''},
        24: { courseCode: '', url: '', runType: ''},
    },
    // Poly Reader
    'PR': {
        1: { courseCode: '7925', url: '/Contents/LCMSContents/143001-144000/143744/index.html', runType: '', fileURL: '/pdf/poly-reader/PR_1st_W01_Colors_e-POLY.pdf', fileName: 'PR_1st_W01_Colors_e-POLY.pdf'},
        2: { courseCode: '9208', url: '/Contents/LCMSContents/145001-146000/145828/index.html', runType: '', fileURL: '/pdf/poly-reader/PR_1st_W02_More Colors_e-POLY.pdf', fileName: 'PR_1st_W02_More Colors_e-POLY.pdf'},
        3: { courseCode: '9209', url: '/Contents/LCMSContents/145001-146000/145830/index.html', runType: '', fileURL: '/pdf/poly-reader/PR_1st_W03_Shapes_e-POLY.pdf', fileName: 'PR_1st_W03_Shapes_e-POLY.pdf'},
        4: { courseCode: '9791', url: '/Contents/LCMSContents/147001-148000/147211/index.html', runType: '', fileURL: '/pdf/poly-reader/PR_1st_W04_Sockheadz Colors_e-POLY.pdf', fileName: 'PR_1st_W04_Sockheadz Colors_e-POLY.pdf'},
        5: { courseCode: '', url: '', runType: ''},
        6: { courseCode: '', url: '', runType: ''},
        7: { courseCode: '', url: '', runType: ''},
        8: { courseCode: '', url: '', runType: ''},
        9: { courseCode: '', url: '', runType: ''},
        10: { courseCode: '', url: '', runType: ''},
        12: { courseCode: '', url: '', runType: ''},
        13: { courseCode: '', url: '', runType: ''},
        14: { courseCode: '', url: '', runType: ''},
        15: { courseCode: '', url: '', runType: ''},
        16: { courseCode: '', url: '', runType: ''},
        17: { courseCode: '', url: '', runType: ''},
        18: { courseCode: '', url: '', runType: ''},
        19: { courseCode: '', url: '', runType: ''},
        20: { courseCode: '', url: '', runType: ''},
        21: { courseCode: '', url: '', runType: ''},
        22: { courseCode: '', url: '', runType: ''},
        23: { courseCode: '', url: '', runType: ''},
        24: { courseCode: '', url: '', runType: ''},
    },
    // sing along
    'SA': {
        1: { courseCode: '7663', url: '/Contents/LCMSContents/143001-144000/143438/index.html', runType: ''},
        2: { courseCode: '9205', url: '/Contents/LCMSContents/145001-146000/145820/index.html', runType: ''},
        3: { courseCode: '9206', url: '/Contents/LCMSContents/145001-146000/145822/index.html', runType: ''},
        4: { courseCode: '9207', url: '/Contents/LCMSContents/145001-146000/145824/index.html', runType: ''},
        5: { courseCode: '', url: '', runType: ''},
        6: { courseCode: '', url: '', runType: ''},
        7: { courseCode: '', url: '', runType: ''},
        8: { courseCode: '', url: '', runType: ''},
        9: { courseCode: '', url: '', runType: ''},
        10: { courseCode: '', url: '', runType: ''},
        12: { courseCode: '', url: '', runType: ''},
        13: { courseCode: '', url: '', runType: ''},
        14: { courseCode: '', url: '', runType: ''},
        15: { courseCode: '', url: '', runType: ''},
        16: { courseCode: '', url: '', runType: ''},
        17: { courseCode: '', url: '', runType: ''},
        18: { courseCode: '', url: '', runType: ''},
        19: { courseCode: '', url: '', runType: ''},
        20: { courseCode: '', url: '', runType: ''},
        21: { courseCode: '', url: '', runType: ''},
        22: { courseCode: '', url: '', runType: ''},
        23: { courseCode: '', url: '', runType: ''},
        24: { courseCode: '', url: '', runType: ''},
    },
    // Phonics Flash Card
    'PF1': {
        1: { currCode: '197997', learningEleCode: 370, fileURL: '/pdf/flashcard/phonics/PR_B1_L1.pdf', fileName: 'PR_B1_L1.pdf'},
        2: { currCode: '198025', learningEleCode: 370, fileURL: '/pdf/flashcard/phonics/PR_B1_L2.pdf', fileName: 'PR_B1_L2.pdf'},
        3: { currCode: '198026', learningEleCode: 370, fileURL: '/pdf/flashcard/phonics/PR_B1_L3.pdf', fileName: 'PR_B1_L3.pdf'},
        4: { currCode: '198027', learningEleCode: 370, fileURL: '/pdf/flashcard/phonics/PR_B1_L4.pdf', fileName: 'PR_B1_L4.pdf'},
        5: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        6: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        7: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        8: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        9: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        10: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        11: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        12: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        13: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        14: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        15: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
    },
     // Read it Flash Card
     'RF1': {
        1: { currCode: '198056', learningEleCode: 376, fileURL: '/pdf/flashcard/read-aloud/RA_U1_L1.pdf', fileName: 'RA_U1_L1.pdf'},
        2: { currCode: '198057', learningEleCode: 376, fileURL: '/pdf/flashcard/read-aloud/RA_U1_L2.pdf', fileName: 'RA_U1_L2.pdf'},
        3: { currCode: '198058', learningEleCode: 376, fileURL: '/pdf/flashcard/read-aloud/RA_U1_L3.pdf', fileName: 'RA_U1_L3.pdf'},
        4: { currCode: '198058', learningEleCode: 376, fileURL: '/pdf/flashcard/read-aloud/RA_U1_L4.pdf', fileName: 'RA_U1_L4.pdf'},
        5: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        6: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        7: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        8: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        9: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        10: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        11: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        12: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        13: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        14: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        15: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
    },
    // Meet & Greet Flash Card
    'MF2': {
        1: { currCode: '198106', learningEleCode: 388, fileURL: '/pdf/flashcard/meet-greet/MG_U1_L1.pdf', fileName: 'MG_U1_L1.pdf'},
        2: { currCode: '198107', learningEleCode: 388, fileURL: '/pdf/flashcard/meet-greet/MG_U1_L2.pdf', fileName: 'MG_U1_L2.pdf'},
        3: { currCode: '198108', learningEleCode: 388, fileURL: '/pdf/flashcard/meet-greet/MG_U1_L3.pdf', fileName: 'MG_U1_L3.pdf'},
        4: { currCode: '198109', learningEleCode: 388, fileURL: '/pdf/flashcard/meet-greet/MG_U1_L4.pdf', fileName: 'MG_U1_L4.pdf'},
        5: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        6: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        7: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        8: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        9: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        10: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        11: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        12: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        13: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        14: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
        15: { currCode: '', learningEleCode: '', fileURL: '', fileName: ''},
    },
};
